#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/
#    username: postgres
#    password: example
#  flyway:
#    enabled: true
#    locations: classpath:db/migration
#    baseline-on-migrate: true

server:
  port: 8127


service:
  integrations:
    payment-service:
      products-url:
        base: "http://localhost:8126/product"
        pid: "/{pid}"
        user: "/user/{uid}"
        accnum: "/accnum/{accnum}"
        update: "/"
